/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateIndexRouteImport } from './routes/donate.index'
import { Route as DonateSuccessRouteImport } from './routes/donate.success'
import { Route as DonateReviewRouteImport } from './routes/donate.review'
import { Route as DonatePaymentRouteImport } from './routes/donate.payment'
import { Route as DonateFlowRouteImport } from './routes/donate.flow'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/donate/success',
  path: '/donate/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateReviewRoute = DonateReviewRouteImport.update({
  id: '/donate/review',
  path: '/donate/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DonatePaymentRoute = DonatePaymentRouteImport.update({
  id: '/donate/payment',
  path: '/donate/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateFlowRoute = DonateFlowRouteImport.update({
  id: '/donate/flow',
  path: '/donate/flow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/programs': typeof ProgramsRoute
  '/donate/flow': typeof DonateFlowRoute
  '/donate/payment': typeof DonatePaymentRoute
  '/donate/review': typeof DonateReviewRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate/': typeof DonateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/programs': typeof ProgramsRoute
  '/donate/flow': typeof DonateFlowRoute
  '/donate/payment': typeof DonatePaymentRoute
  '/donate/review': typeof DonateReviewRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate': typeof DonateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/programs': typeof ProgramsRoute
  '/donate/flow': typeof DonateFlowRoute
  '/donate/payment': typeof DonatePaymentRoute
  '/donate/review': typeof DonateReviewRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate/': typeof DonateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/get-involved'
    | '/impact'
    | '/programs'
    | '/donate/flow'
    | '/donate/payment'
    | '/donate/review'
    | '/donate/success'
    | '/donate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/get-involved'
    | '/impact'
    | '/programs'
    | '/donate/flow'
    | '/donate/payment'
    | '/donate/review'
    | '/donate/success'
    | '/donate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/get-involved'
    | '/impact'
    | '/programs'
    | '/donate/flow'
    | '/donate/payment'
    | '/donate/review'
    | '/donate/success'
    | '/donate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  ProgramsRoute: typeof ProgramsRoute
  DonateFlowRoute: typeof DonateFlowRoute
  DonatePaymentRoute: typeof DonatePaymentRoute
  DonateReviewRoute: typeof DonateReviewRoute
  DonateSuccessRoute: typeof DonateSuccessRoute
  DonateIndexRoute: typeof DonateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/donate/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/review': {
      id: '/donate/review'
      path: '/donate/review'
      fullPath: '/donate/review'
      preLoaderRoute: typeof DonateReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/payment': {
      id: '/donate/payment'
      path: '/donate/payment'
      fullPath: '/donate/payment'
      preLoaderRoute: typeof DonatePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/flow': {
      id: '/donate/flow'
      path: '/donate/flow'
      fullPath: '/donate/flow'
      preLoaderRoute: typeof DonateFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  ProgramsRoute: ProgramsRoute,
  DonateFlowRoute: DonateFlowRoute,
  DonatePaymentRoute: DonatePaymentRoute,
  DonateReviewRoute: DonateReviewRoute,
  DonateSuccessRoute: DonateSuccessRoute,
  DonateIndexRoute: DonateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
